language: php

sudo: false

git:
  depth: 3

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  npm: true

php:
  # - 5.6
  # - 7.0
  # - 7.1
  - 7.2
  # - nightly

matrix:
  fast_finish: true
  # allow_failures:
  #   - php: nightly

before_script:
  - npm i

install:
  - composer install
  - nvm install 10
  - nvm use 10

script:
  - npm run lint
