language: php

sudo: false

git:
  depth: 3

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  yarn: true

php:
  # - 5.6
  # - 7.0
  # - 7.1
  - 7.2
  # - nightly

matrix:
  fast_finish: true
  # allow_failures:
  #   - php: nightly

before_script:
  - yarn

install:
  - composer install
  - nvm install 10
  - nvm use 10
  - npm i -g yarn

script:
  - yarn lint
